from django.urls import path

from .views import (
    DefaultFormByFieldView,
    DefaultFormsetView,
    FormHorizontalView,
    FormInlineView,
    FormWithFilesView,
    HomePageView,
    MiscView,
    PaginationView,
    MaterielEnregistreView,
    nouveau_materiel,
    SortieMaterielView,
    inventaire,
    RepairConfigureView,
    BilanAnnuelView,
    BilanEcologicView,
    EtatStockView,
    MonCompteView,
    DetailsPcView,
)

urlpatterns = [
    path("", HomePageView.as_view(), name="home"),
    path("formset", DefaultFormsetView.as_view(), name="formset_default"),
    path("nouveau_materiel", nouveau_materiel, name="nouveau_materiel"),
    path("sortie_materiel", SortieMaterielView.as_view(), name="sortie_materiel"),
    path("materiel_enregistre/<materiel_id>", MaterielEnregistreView.as_view(), name="materiel_enregistre"),
    path("inventaire", inventaire, name="inventaire"),
    path("reparer_et_configurer", RepairConfigureView.as_view(), name="reparer_et_configurer"),
    path("bilan_annuel", BilanAnnuelView.as_view(), name="bilan_annuel"),
    path("bilan_ecologic", BilanEcologicView.as_view(), name="bilan_ecologic"),
    path("etat_stock", EtatStockView.as_view(), name="etat_stock"),
    path("mon_compte", MonCompteView.as_view(), name="mon_compte"),
    path("details_pc/<materiel_id>", DetailsPcView.as_view(), name="details_pc"),
    path("form_by_field", DefaultFormByFieldView.as_view(), name="form_by_field"),
    path("form_horizontal", FormHorizontalView.as_view(), name="form_horizontal"),
    path("form_inline", FormInlineView.as_view(), name="form_inline"),
    path("form_with_files", FormWithFilesView.as_view(), name="form_with_files"),
    path("pagination", PaginationView.as_view(), name="pagination"),
    path("misc", MiscView.as_view(), name="misc"),
]
