# Generated by Django 6.0.3 on 2026-03-24 23:57

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficiaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('adresse', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Materiel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_inventaire', models.CharField(blank=True, max_length=20, unique=True)),
                ('type_materiel', models.CharField(choices=[('PC', 'Ordinateur'), ('ECRAN', 'Écran'), ('PERIPH', 'Périphérique')], default='PC', max_length=10)),
                ('modele', models.CharField(blank=True, max_length=100)),
                ('numero_serie', models.CharField(blank=True, max_length=100)),
                ('date_entree', models.DateField(default=django.utils.timezone.now)),
                ('poids_entree_kg', models.DecimalField(decimal_places=3, default=0, max_digits=6)),
                ('provenance', models.CharField(blank=True, max_length=200)),
                ('statut', models.CharField(choices=[('ENTREE', 'En attente de diagnostic'), ('DIAGNOSTIC', 'En cours de diagnostic'), ('REPARATION', 'En cours de réparation'), ('PRET_A_DON', 'Réparé - Prêt à donner'), ('DONNE', 'Donné'), ('RECYCLAGE', 'Envoyé au recyclage'), ('PERDU', 'Perdu / Volé')], default='ENTREE', max_length=20)),
                ('date_prise_en_charge', models.DateTimeField(blank=True, null=True)),
                ('date_sortie', models.DateTimeField(blank=True, null=True)),
                ('poids_sortie_kg', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('organisme_recyclage', models.CharField(blank=True, max_length=100)),
                ('beneficiaire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materiaux_recus', to='inventaire.beneficiaire')),
                ('benevole_en_charge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materiaux_en_charge', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_entree'],
            },
        ),
        migrations.CreateModel(
            name='Marque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('site_web', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Marques',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Benevole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('specialites', models.JSONField(blank=True, default=list, help_text='Cochez les domaines de compétence', verbose_name='Spécialités')),
                ('actif', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile_benevole', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bénévole',
                'verbose_name_plural': 'Bénévoles',
            },
        ),
        migrations.CreateModel(
            name='Ecran',
            fields=[
                ('materiel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='inventaire.materiel')),
                ('diagonale_pouces', models.CharField(blank=True, choices=[('13.3', '13.3" (34 cm)'), ('14.0', '14.0" (36 cm)'), ('15.6', '15.6" (40 cm)'), ('21.5', '21.5" (55 cm)'), ('23.8', '23.8" (60 cm)'), ('24.0', '24" (61 cm)'), ('27.0', '27" (69 cm)'), ('32.0', '32" (81 cm)'), ('Autre', 'Autre')], max_length=10)),
                ('resolution', models.CharField(blank=True, max_length=20)),
                ('connectique', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'Écran',
                'verbose_name_plural': 'Écrans',
            },
            bases=('inventaire.materiel',),
        ),
        migrations.CreateModel(
            name='Ordinateur',
            fields=[
                ('materiel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='inventaire.materiel')),
                ('categorie', models.CharField(choices=[('FIXE', 'PC Fixe / Tour'), ('PORTABLE', 'PC Portable'), ('ALL_IN_ONE', 'All-in-One')], default='FIXE', max_length=20)),
                ('cpu', models.CharField(blank=True, max_length=100)),
                ('cpu_score', models.PositiveIntegerField(blank=True, help_text='Indice PassMark (https://www.cpubenchmark.net/). Si < 800 : recyclage recommandé.', null=True)),
                ('ram_go', models.PositiveIntegerField(default=0)),
                ('ram_nb_barrettes', models.PositiveIntegerField(default=1)),
                ('ram_type', models.CharField(choices=[('DDR2', 'DDR2'), ('DDR3', 'DDR3'), ('DDR3L', 'DDR3 Low Voltage'), ('DDR4', 'DDR4'), ('DDR5', 'DDR5'), ('SODIMM', 'SODIMM'), ('INCONNUE', 'Inconnue')], default='INCONNUE', max_length=20)),
                ('a_alimentation', models.BooleanField(default=True)),
                ('etat_batterie', models.CharField(choices=[('N/A', 'Non concerné'), ('EXCELLENT', 'Comme neuve'), ('BON', 'Correcte'), ('FAIBLE', 'Faible'), ('HS', 'HS'), ('INCONNUE', 'Non testée')], default='N/A', max_length=20)),
                ('ecran_diagonale_pouces', models.CharField(blank=True, choices=[('13.3', '13.3" (34 cm)'), ('14', '14" (36 cm)'), ('15.6', '15.6" (40 cm)'), ('16', '16" (40.6 cm)'), ('17.3', '17.3" (44 cm)'), ('AUTRE', 'Autre')], max_length=10)),
                ('a_carte_graphique_dediee', models.BooleanField(default=False)),
                ('modele_gpu', models.CharField(blank=True, max_length=100)),
                ('a_carte_wifi', models.BooleanField(default=False, help_text="Présence d'une carte WiFi (interne ou clé USB fournie). Crucial pour les Tours.")),
                ('linux_installe', models.BooleanField(default=False)),
                ('linux_distro', models.CharField(blank=True, choices=[('ANDUIN', 'AnduinOS'), ('ZORIN', 'Zorin OS'), ('UBUNTU', 'Ubuntu'), ('LINUX_MINT', 'Linux Mint'), ('AUTRE', 'Autre')], max_length=50)),
                ('date_maj_os', models.DateField(blank=True, null=True)),
                ('onlyoffice_installe', models.BooleanField(default=False)),
                ('logiciel_photo', models.CharField(blank=True, choices=[('AUCUN', 'Aucun'), ('GIMP', 'GIMP'), ('PHOTOFLARE', 'Photoflare'), ('DARKTABLE', 'Darktable')], max_length=50)),
                ('media_player', models.CharField(blank=True, choices=[('VLC', 'VLC'), ('DEFAULT', 'Défaut OS'), ('MPV', 'MPV')], max_length=50)),
                ('firefox_configure', models.BooleanField(default=False)),
                ('pieces_changees', models.TextField(blank=True)),
                ('cout_reparation', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
            ],
            options={
                'verbose_name': 'Ordinateur',
                'verbose_name_plural': 'Ordinateurs',
            },
            bases=('inventaire.materiel',),
        ),
        migrations.CreateModel(
            name='Peripherique',
            fields=[
                ('materiel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='inventaire.materiel')),
                ('type_periph', models.CharField(choices=[('CLAVIER', 'Clavier'), ('SOURIS', 'Souris'), ('WEBCAM', 'Webcam'), ('CASQUE', 'Casque'), ('ENCEINTES', 'Enceintes'), ('HUB', 'Hub USB'), ('AUTRE', 'Autre')], default='AUTRE', max_length=20)),
                ('connectique', models.CharField(blank=True, max_length=50)),
                ('avec_cable', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Périphérique',
                'verbose_name_plural': 'Périphériques',
            },
            bases=('inventaire.materiel',),
        ),
        migrations.CreateModel(
            name='Intervention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_heure', models.DateTimeField(auto_now_add=True)),
                ('type_action', models.CharField(choices=[('DIAG', 'Diagnostic'), ('REPA', 'Réparation'), ('NOTE', 'Note interne'), ('TRANSFERT', 'Transfert de prise en charge'), ('SORTIE', 'Sortie (Don/Recyclage)')], default='NOTE', max_length=20)),
                ('commentaire', models.TextField()),
                ('benevole', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interventions_faites', to=settings.AUTH_USER_MODEL)),
                ('materiel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interventions', to='inventaire.materiel')),
            ],
            options={
                'verbose_name': 'Intervention',
                'verbose_name_plural': 'Interventions',
                'ordering': ['-date_heure'],
            },
        ),
        migrations.AddField(
            model_name='materiel',
            name='marque',
            field=models.ForeignKey(blank=True, help_text='Marque du matériel', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='materiaux', to='inventaire.marque'),
        ),
        migrations.CreateModel(
            name='DisqueDur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_inventaire_disque', models.CharField(blank=True, help_text='Uniquement si testé! Format obligatoire : DSK-0001', max_length=20, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Le format doit être DSK- suivi de 4 chiffres (ex: DSK-0042).', regex='^DSK-\\d{4}$')], verbose_name='N° Inventaire Disque')),
                ('capacite_go', models.PositiveIntegerField()),
                ('type_disque', models.CharField(choices=[('HDD', 'HDD (Mécanique)'), ('SSD', 'SSD (SATA)'), ('NVME', 'SSD (NVMe)'), ('HYBRIDE', 'SSHD')], default='HDD', max_length=10)),
                ('marque', models.CharField(blank=True, max_length=100)),
                ('modele', models.CharField(blank=True, max_length=100)),
                ('numero_serie', models.CharField(blank=True, max_length=100)),
                ('est_sain', models.BooleanField(default=True)),
                ('contient_donnees', models.BooleanField(default=False)),
                ('ordinateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disques', to='inventaire.ordinateur')),
            ],
            options={
                'verbose_name': 'Disque Dur',
                'verbose_name_plural': 'Disques Durs',
                'ordering': ['numero_inventaire_disque', 'type_disque'],
            },
        ),
    ]
