# Generated by Django 6.0.3 on 2026-03-19 12:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MaterielReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marque', models.CharField(max_length=100)),
                ('modele', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventaire.categorie')),
            ],
        ),
        migrations.CreateModel(
            name='Equipement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_inventaire', models.CharField(max_length=100, unique=True)),
                ('date_entree', models.DateField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('STOCK', 'En stock'), ('EN_COURS', 'En cours'), ('POUR_PIECE', 'Pour pièce'), ('A_RECYCLER', 'A recycler')], default='STOCK', max_length=20)),
                ('date_attribution', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventaire.materielreference')),
            ],
        ),
    ]
