# Generated by Django 5.2.1 on 2026-03-20 14:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Materiel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_inventaire', models.CharField(blank=True, editable=False, max_length=20, unique=True)),
                ('date_achat', models.DateField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('STOCK', 'En stock'), ('ASSIGNE', 'Assigné'), ('PANNE', 'En panne'), ('RECYCLE', 'Recyclé')], default='STOCK', max_length=20)),
                ('date_attribution', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Marque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marque', models.CharField(max_length=100, unique=True)),
                ('site_web', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Marques',
                'ordering': ['marque'],
            },
        ),
        migrations.CreateModel(
            name='Ecran',
            fields=[
                ('materiel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='inventaire.materiel')),
                ('diagonale_pouces', models.DecimalField(choices=[('21.5', '21.5 pouces'), ('23.8', '23.8 pouces'), ('24', '24 pouces'), ('25', '25 pouces'), ('27', '27 pouces'), ('32', '32 pouces'), ('34', '34 pouces'), ('40', '40 pouces'), ('43', '43 pouces'), ('49', '49 pouces'), ('55', '55 pouces'), ('65', '65 pouces'), ('75', '75 pouces'), ('86', '86 pouces'), ('98', '98 pouces')], decimal_places=1, help_text="Sélectionnez la diagonale de l'écran", max_digits=4)),
                ('modele', models.CharField(blank=True, max_length=100)),
                ('resolution', models.CharField(blank=True, max_length=20)),
                ('connectique', models.CharField(blank=True, max_length=100)),
                ('marque', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ecrans', to='inventaire.marque')),
            ],
            options={
                'verbose_name': 'Écran',
                'verbose_name_plural': 'Écrans',
                'ordering': ['diagonale_pouces'],
            },
            bases=('inventaire.materiel',),
        ),
        migrations.CreateModel(
            name='Ordinateur',
            fields=[
                ('materiel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='inventaire.materiel')),
                ('modele', models.CharField(blank=True, max_length=100)),
                ('cpu', models.CharField(blank=True, max_length=100)),
                ('ram_go', models.PositiveIntegerField()),
                ('stockage_go', models.PositiveIntegerField()),
                ('type_stockage', models.CharField(choices=[('SSD', 'SSD'), ('HDD', 'HDD'), ('NVMe', 'NVMe')], default='SSD', max_length=20)),
                ('systeme_exploitation', models.CharField(blank=True, max_length=50)),
                ('marque', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordinateurs', to='inventaire.marque')),
            ],
            options={
                'verbose_name': 'Ordinateur',
                'verbose_name_plural': 'Ordinateurs',
            },
            bases=('inventaire.materiel',),
        ),
    ]
