# Generated by Django 6.0.3 on 2026-03-25 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventaire', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='materiel',
            name='provenance_precisions',
            field=models.CharField(blank=True, help_text="Précisez le nom si 'Autre' est sélectionné", max_length=200),
        ),
        migrations.AlterField(
            model_name='materiel',
            name='numero_inventaire',
            field=models.CharField(blank=True, editable=False, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='materiel',
            name='provenance',
            field=models.CharField(choices=[('sictom_nogent', 'Sictom Nogent'), ('sictom_thirons', 'Sictom Thirons'), ('dechetterie_autre', 'Autre déchetterie'), ('lycee_sully', 'Lycée Sully'), ('partenariat_autre', 'Autre partenariat'), ('don_prive', 'Don privé'), ('don_public', 'Don du secteur public'), ('don_entreprise', "Don d'entreprise"), ('don_asso', "Don d'association")], default='sictom_nogent', help_text='Origine du matériel', max_length=30),
        ),
    ]
