# Generated by Django 6.0.3 on 2026-04-11 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventaire', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordinateur',
            name='dns_configures',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ordinateur',
            name='firefox_extensions',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ordinateur',
            name='langue_configuree',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ordinateur',
            name='rapport_configuration',
            field=models.TextField(blank=True, help_text="Merci d'indiquer les spécificités de configuration logicielle : distribution et version si non standard, autres logiciels installés, autres comptes créés, problèmes rencontrés, etc."),
        ),
        migrations.AlterField(
            model_name='ordinateur',
            name='linux_distro',
            field=models.CharField(blank=True, choices=[('ANDUIN_LTS_1_1', 'AnduinOS LTS 1.1'), ('ANDUIN_1_4', 'AnduinOS 1.4'), ('ZORIN_18', 'Zorin OS 18 Core'), ('POPOS_LTS_24', 'Pop!_OS 24.04 LTS'), ('POPOS_LTS_24_NVIDIA', 'Pop!_OS 24.04 LTS with NVIDIA'), ('UBUNTU_LTS_24', 'Ubuntu LTS 24'), ('UBUNTU_25', 'Ubuntu 25'), ('UBUNTU_SERVER_LTS_24', 'Ubuntu Server LTS 24'), ('AUTRE', 'Autre (préciser dans le rapport)')], max_length=50),
        ),
        migrations.AlterField(
            model_name='ordinateur',
            name='logiciel_photo',
            field=models.CharField(blank=True, choices=[('AUCUN', 'Aucun'), ('GIMP', 'GIMP'), ('DARKTABLE', 'Darktable'), ('PHOTOFLARE', 'Photoflare'), ('PINTA', 'Pinta')], max_length=50),
        ),
        migrations.AlterField(
            model_name='ordinateur',
            name='media_player',
            field=models.CharField(blank=True, choices=[('DEFAULT', 'Défaut OS'), ('CELLULOID', 'Celluloid'), ('HARUNA', 'Haruna'), ('MPV', 'MPV'), ('VLC', 'VLC')], default='DEFAULT', max_length=50),
        ),
    ]
