# Generated by Django 6.0.3 on 2026-04-08 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventaire', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materiel',
            name='rapport_diagnostic',
            field=models.TextField(blank=True),
        ),
    ]
