# Generated by Django 6.0.3 on 2026-04-11 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventaire', '0002_ordinateur_dns_configures_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordinateur',
            name='media_player',
            field=models.CharField(blank=True, choices=[('DEFAULT', 'Défaut OS'), ('CELLULOID', 'Celluloid'), ('HARUNA', 'Haruna'), ('MPV', 'MPV'), ('VLC', 'VLC')], max_length=50),
        ),
    ]
