# Generated by Django 6.0.3 on 2026-04-09 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventaire', '0002_alter_materiel_rapport_diagnostic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materiel',
            name='statut',
            field=models.CharField(choices=[('ENTREE', 'En attente de diagnostic'), ('DIAGNOSTIC', 'En cours de diagnostic'), ('ATTENTE_PIECES', 'En attente de pièces'), ('POUR_PIECES', 'En attente de récupération de pièces avant recyclage'), ('EN_COURS_DEMONTAGE', 'En cours de démontage'), ('CONFIGURATION', "En cours d'installation OS et logiciels"), ('PRET_A_DON', 'Réparé, prêt à donner'), ('DONNE', 'Donné'), ('RECYCLAGE', 'Envoyé au recyclage'), ('PERDU', 'Perdu / Volé')], default='ENTREE', max_length=20),
        ),
    ]
