# Generated by Django 6.0.3 on 2026-03-25 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventaire', '0002_materiel_provenance_precisions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='materiel',
            name='rapport_diagnostic',
            field=models.TextField(blank=True),
        ),
    ]
