# Generated by Django 6.0.3 on 2026-03-28 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventaire', '0003_materiel_rapport_diagnostic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materiel',
            name='statut',
            field=models.CharField(choices=[('ENTREE', 'En attente de diagnostic'), ('DIAGNOSTIC', 'En cours de diagnostic'), ('ATTENTE_PIECES', 'En attente de pièces'), ('REPARATION', 'En cours de configuration'), ('PRET_A_DON', 'Prêt à donner'), ('DONNE', 'Donné'), ('RECYCLAGE', 'Recyclé'), ('PERDU', 'Perdu / Volé')], default='ENTREE', max_length=20),
        ),
    ]
