# Generated by Django 6.0.3 on 2026-04-12 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventaire', '0003_alter_ordinateur_media_player'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intervention',
            name='type_action',
            field=models.CharField(choices=[('DIAG', 'Diagnostic et réparation'), ('CONFIG', 'Configuration OS et logicielle'), ('NOTE', 'Note de travail'), ('TRANSFERT', 'Transfert de prise en charge'), ('SORTIE', 'Sortie (don/recyclage)')], default='NOTE', max_length=20),
        ),
    ]
