# Generated by Django 6.0.3 on 2026-04-09 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventaire', '0003_alter_materiel_statut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordinateur',
            name='cpu',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='ordinateur',
            name='disque_principal_type',
            field=models.CharField(blank=True, choices=[('HDD', 'HDD (Mécanique)'), ('SSD', 'SSD (SATA)'), ('NVME', 'SSD (NVMe)'), ('HYBRIDE', 'SSHD')], max_length=10),
        ),
        migrations.AlterField(
            model_name='ordinateur',
            name='disque_secondaire_type',
            field=models.CharField(blank=True, choices=[('HDD', 'HDD (Mécanique)'), ('SSD', 'SSD (SATA)'), ('NVME', 'SSD (NVMe)'), ('HYBRIDE', 'SSHD')], max_length=10),
        ),
    ]
