# Generated by Django 6.0.3 on 2026-04-09 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventaire', '0004_alter_ordinateur_cpu_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materiel',
            name='statut',
            field=models.CharField(choices=[('ENTREE', 'Attente de diagnostic'), ('DIAGNOSTIC', 'Diagnostic en cours'), ('ATTENTE_PIECES', 'En attente de pièces'), ('POUR_PIECES', 'Pour pièces'), ('EN_COURS_DEMONTAGE', 'Démontage en cours'), ('CONFIGURATION', 'Installation'), ('PRET_A_DON', 'Prêt à donner'), ('DONNE', 'Donné'), ('RECYCLAGE', 'Recyclé'), ('PERDU', 'Perdu / volé')], default='ENTREE', max_length=20),
        ),
        migrations.AlterField(
            model_name='ordinateur',
            name='ram_nb_barrettes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
