# Generated by Django 6.0.3 on 2026-04-02 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventaire', '0004_alter_materiel_statut'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='materiel',
            options={'ordering': ['-date_entree'], 'permissions': [('can_print_labels', 'Peut imprimer les étiquettes et rapports'), ('can_validate_don', 'Peut valider les dons aux bénéficiaires')]},
        ),
    ]
